# Generated by Django 5.2.6 on 2025-09-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LiteraryGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number_page', models.IntegerField(blank=True, null=True)),
                ('year_publication', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_author', to='books.author')),
                ('literary_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_genre', to='books.literarygenre')),
            ],
        ),
    ]
