# Generated by Django 5.2.6 on 2025-09-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_publication',
            new_name='publication_year',
        ),
    ]
