# Generated by Django 5.2.6 on 2025-09-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_year_publication_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='literarygenre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
