# Generated by Django 5.2.6 on 2025-10-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_created_by'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='literary_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_genre', to='genres.literarygenre'),
        ),
        migrations.DeleteModel(
            name='LiteraryGenre',
        ),
    ]
