# Generated by Django 5.2.6 on 2025-10-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0007_alter_book_literary_genre_delete_literarygenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_author', to='authors.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
